[tool.mccole]
skips = ["CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "templates"]

[tool.mccole.renames]
"README.md" = ""
"bibliography.md" = "bibliography"
"glossary.md" = "glossary"
"LICENSE.md" = "license"
